### ISSUE TITLE
Design Mocks

### ISSUE THREAD

**Issue by MasonSchneider** [WrightJosh/SeniorProject#1]
Hey,

We started working on mocks. Here's an image of what we started thinking about. We have some questions about the "security device" as well as how the Authorities vs Certificates should work. Sorry for the poor drawing, once we get a better idea this will all be digital on ninja mock.
![2015-03-29 17 15 11](https://cloud.githubusercontent.com/assets/1763130/6888204/8c5b6eda-d644-11e4-8899-ba2ecbe9cf0d.jpg)

**Comment by MasonSchneider** [comment]
What we ended up with at the end of the meeting was the idea that a list of Authorities with a way to view detailed information about each and another list with the certificates from those authorities may be our best approach. That way details about each could be viewed. The things we don't like about this is that you have to click buttons to see the specific certificates/info about the authority. We're thinking another way to organize this is a list of authorities with a sub-list of certificates for that authority.

**Comment by WilsonKathleen** [comment]
Looks like a good start.

> > questions about the "security device"
> > "Builtin Object Token" means that the certificate is included in the NSS root store.
> > "Software Security Device" means that the certificate is not in the default list (not in the NSS root store).
> > This terminology is not user-friendly, so feel free to change the text to something more user friendly.
> > 
> > We're thinking another way to organize this is a list of authorities 
> > with a sub-list of certificates for that authority.

That sounds fine. The user should be able to see all of the trusted certs at once.

I think for each certificate in the list the user should be able to see right away which certificates are trusted, and what they are trusted for.

Brainstorming options (these are not mutually exclusive)...

One option is to display the trust bit settings for each cert. (like in the drawing where you have the checkboxes)

Another option is to give the user a way to see the authorities/certs that are trusted each use; e.g. switch something to show the authorities/certs that are trusted for SSL/TLS, then switch again to see the authorities/certs that are trusted for S/MIME, then switch again to see the authorities/certs that are trusted for Code Signing, then switch again to see the full list.

A user who accesses the Certificate Manager from Firefox is most likely interested in seeing the authorities/certs that are trusted for SSL/TLS, so one option is to have the default view only show those authorities/certs that are trusted for SSL/TLS, and then the user would have to switch something to see the full list and trust bit settings for each cert.

**Comment by MasonSchneider** [comment]
Here's a link to the ninjamock. http://ninjamock.com/s/pujiof
We had more of the pages on there but the site crashed and we lost progress.
We don't plan on using this site anymore because of their recent changes.

**Comment by sidstamm** [comment]
Where do you intend to put the mocks (if you make new ones)?

**Comment by MasonSchneider** [comment]
We'll probably stick to actual drawings and then use something simple like google drawings to digitize it.
