### ISSUE TITLE
Add 'CA Country Code' which is retrieved directly from one of the CA's root certs

### ISSUE THREAD

**Issue by WilsonKathleen** [WrightJosh/SeniorProject#13]
## Please add 'CA Country Code' which can be pulled directly from the 'C' in the Issuer Field of one of the CA's root certificates.

For example, the details of Atos would change to:
Last Audit: 2015.07.01
Geographic Focus:   Europe
CA Country Code: DE

**Comment by MasonSchneider** [comment]
Should country code be another field that is searched through the search bar or should it just be name, geographic focus, and owner?

**Comment by WilsonKathleen** [comment]
It would be nice (not required) if country code could be searched, but that might be too difficult -- too many search results matching the two-letter country codes...

**Comment by MasonSchneider** [comment]
Yeah, it wouldn't be difficult to add but it would make the search less accurate as you mentioned.
