### ISSUE TITLE
Make sure all text operations are using UTF8

### ISSUE THREAD

**Issue by WilsonKathleen** [WrightJosh/SeniorProject#16]
Please check to make sure all text is UTF8.

Cert to test with:
http://pki.gov.kz/cert/pki_rsa.cer 
(be sure to remove this one after you finish testing, as this government CA has publicly stated that they do MITM)

I imported this cert, but cannot find it in the Authorities list. 
In the old Cert Manager it shows up at the very bottom.

**Comment by melissapthai** [comment]
I imported the given certificate, and it seems to show as expected (also at the bottom of the screen).

Authority view:
![capture](https://cloud.githubusercontent.com/assets/3220734/12225104/993bb89e-b7d0-11e5-9cbf-81b33fdadfb4.PNG)

Cert view:
![capture2](https://cloud.githubusercontent.com/assets/3220734/12225105/9d85cc96-b7d0-11e5-89a2-01fb81a9cb21.PNG)

**Comment by MasonSchneider** [comment]
I've added a meta tag to the addon to force UTF-8.
