### ISSUE TITLE
Create a way to maintain removed salesforce info and instructions on how to update

### ISSUE THREAD

**Issue by MasonSchneider** [WrightJosh/SeniorProject#17]
[Related correspondence here](https://github.com/WrightJosh/SeniorProject/issues/8)

**Comment by MasonSchneider** [comment]
Can you write instructions on how the salesforce script is ran and how to update the data? Put it in the readme maybe?

**Comment by MasonSchneider** [comment]
Include python version etc

**Comment by MasonSchneider** [comment]
Instructions [here](https://github.com/WrightJosh/SeniorProject/commit/95c3e6bcdfedbcd8f559d39c2a6c418b7e3f73aa)

**Comment by WilsonKathleen** [comment]
Please remember that I am no longer a developer, so my github skills are extremely limited (and I'm not even sure if I have Python installed). 
Would you please append these instructions with a list of the terminal commands to achieve this?
i.e. start a new terminal window and perform each step (starting with getting the latest version from github, and ending with checking the new SalesForceData.js back into github), then list all of the commands that you entered into your terminal window, and append that list to the instructions.

**Comment by redaxed** [comment]
I tried to make them easier to read let me know if you have any trouble.
