### ISSUE TITLE
TypeErrors in console

### ISSUE THREAD

**Issue by mozkeeler** [WrightJosh/SeniorProject#20]
I'm getting some errors in the console on linux (using nightly):

console.error: certmanager: 
Object
    - _errorType = TypeError
    - message = document.getElementById(...) is null
    - fileName = resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://certmanager/data/scripts/inject.js
    - lineNumber = 13
    - stack = @resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://certmanager/data/scripts/inject.js:13:1|
    - name = TypeError

**Comment by cbhrocks** [comment]
Do you know exactly when this occurs? or is it just happening randomly during use? so far I haven't been able to replicate it.

**Comment by mozkeeler** [comment]
I don't think I've seen this in a while, actually. I'll reopen if I can reproduce.
