### ISSUE TITLE
Refresh Certificates window/list after importing a cert

### ISSUE THREAD

**Issue by WilsonKathleen** [WrightJosh/SeniorProject#24]
When in the Certificates window, when you click on the "Import..." button and import a root cert, the window should refresh to show that the cert was actually added.

**Comment by burchtm** [comment]
This issue has been resolved. During resolution it was discovered that there are some inefficiencies with how this must be handled in code which will be explored and resolved in a separate issue which will be opened.

**Comment by sidstamm** [comment]
What resolved the issue?  Was it changeset 82fccfa?

**Comment by burchtm** [comment]
Yes, I just forgot to put closes in the comment. I have opened another issue for some inefficiencies that I discovered in this process.
