### ISSUE TITLE
Please add a "View All Certificates" option/button

### ISSUE THREAD

**Issue by WilsonKathleen** [WrightJosh/SeniorProject#25]
Please add a way to list all of the certificates at once. i.e. be able to see all of the certificates, regardless of which CA owns them. The list should be alphabetically sorted according to the certificate name.

**Comment by WilsonKathleen** [comment]
Any update on this issue?
Once this ability is added (so there is complete feature parity with the built in cert manager), I will tell folks in the mozilla.dev.security.policy forum about this add-on.
Thanks!

**Comment by WilsonKathleen** [comment]
I like the user interface for this -- the 'View All Authorities' or 'View All Certificates' interface at the top right corner of the window. It doesn't appear to be functional yet, but I am looking forward to using it when it is ready.  Thanks!

**Comment by cheungnj** [comment]
@WilsonKathleen I noticed that when a certificate does not have a common name, the certificate's name will be displayed as "Certificate for [AUTHORITY]". Should I alphabetize these certificates under "C" or display these before or after the alphabetized list?

**Comment by WilsonKathleen** [comment]
When the certificate does not have a CN, it would be ideal if you can use the "Friendly Name". This is what the old Certificate Manager does, so there must be a way to get it.
To view the old Cert Manager:
Firefox->Preferences->Advanced->Certificates->View Certificates->Authorities
example: VeriSign Class 3 Public Primary Certificate Authority

**Comment by WilsonKathleen** [comment]
I think the "Friendly Name" is the CKA_LABEL in 
http://mxr.mozilla.org/mozilla-release/source/security/nss/lib/ckfw/builtins/certdata.txt

**Comment by cheungnj** [comment]
Closed. Changeset 6c0204406be85fba7324f6e8d4a94f9a17924906 resolves this issue.

**Comment by WilsonKathleen** [comment]
Yay! I'm looking forward to trying it out.  Please let me know the new weekly schedule for when updated versions  of https://github.com/sidstamm/FirefoxCertificateManager/blob/master/%40certmanager.xpi will be available.
