### ISSUE TITLE
Salesforce

### ISSUE THREAD

**Issue by MasonSchneider** [WrightJosh/SeniorProject#3]
Hello,
We're currently working on the UI. We were wondering if we could get access to the SalesForce data so we can get an idea of what fields we need to display.
Thanks!

**Comment by WilsonKathleen** [comment]
Hi there,
Do you need direct access to SalesForce?

Or, can you pull the data from the spreadsheets that I publish weekly?
https://wiki.mozilla.org/CA:IncludedCAs
https://wiki.mozilla.org/CA:PendingCAs

Note: I will be adding "Geographic Focus" to the IncludedCAs spreadsheet, in the same place I have it in the PendingCAs spreadsheet.  When will you need it?

Thanks,
Kathleen

**Comment by MasonSchneider** [comment]
We noticed you added the new Geographic Focus column but that it isn't accessible in CSV form. Is there a way to get this?
Thanks!

**Comment by WilsonKathleen** [comment]
I will get you the CSV form of the report by next week.
I will also finish filling in Geographic Focus this week.
Thanks!

**Comment by WilsonKathleen** [comment]
Here you go: https://mozillacaprogram.secure.force.com/CA/IncludedCACertificateReportCSVFormat

**Comment by MasonSchneider** [comment]
Thank you!
