### ISSUE TITLE
Inefficiencies in post-import tasks

### ISSUE THREAD

**Issue by burchtm** [WrightJosh/SeniorProject#31]
Currently, whenever a new certificate is imported both the main table and the detail table are updated. This should not be the case as it is inefficient to update both tables when it is not needed. The details table should only be update on import if you are on the certificate page and the main table should only update if you are on the main page.

**Comment by cheungnj** [comment]
Fixed. See 311a48677be12004ab13274d9ae5b4f9421fe68b
