### ISSUE TITLE
Verify and implement the addon handling the root store changing underneath it

### ISSUE THREAD

**Issue by burchtm** [WrightJosh/SeniorProject#36]
From issue #33 Kathleen stated:

"Regarding: Developer Edition has extra authority "Krajowa Izba Rozliczeniowa S.A." and the authority "Autoridad de Certificacion Firmaprofesional CIF A62634068" shows blank instead of the name for some reason on the development version. The regular edition has the extra authority "NetLock Halozatbiztonsagi Kft"

Indeed, the KIR root certificate was added in Firefox 46, and other root certificates were added and removed. Please see https://bugzilla.mozilla.org/show_bug.cgi?id=1247990

The Cert Manager Add-On needs to be able to handle having the root store change out underneath it, depending on which version of Firefox is being run. We add, remove, and change trust bits for root certificates frequently.

The data in the CSV file that is generated from Salesforce may not be in sync with the particular version of Firefox that the user is running. The code should be able to deal with such differences."

**Comment by sidstamm** [comment]
There are two possible problems: 1. salesforce CSV too new for the version of the browser's built-in db, and 2. built-in cert db is too new for the extension.

I think the most likely problem is if the browser extension (and salesforce data) is older than the cert db.  This would happen if I install the cert manager, then update Firefox.  Testing this would require an old firefox (35?) and an old salesforce DB.

Ideally the extension would auto-update the salesforce database without a user needing to update the extension, but that's a new feature request.

**Comment by burchtm** [comment]
I am closing this issue as we believe that it is working correctly. We can reopen the issue if we find that this isn't the case going forward.
