### ISSUE TITLE
back button doesn't work correctly

### ISSUE THREAD

**Issue by sidstamm** [WrightJosh/SeniorProject#38]
It would be nice if I could use the browser's back button instead of clicking the <.  

The History API might be handy for fixing this (already built into Firefox):
https://developer.mozilla.org/en-US/docs/Web/API/History_API

**Comment by burchtm** [comment]
This has been fixed in changesets 317a4d7 cb0afbd and dbe0e3b using the history api. Refreshing the page still redirects to index.html and will be worked on for issue #41
