### ISSUE TITLE
Search Capability?

### ISSUE THREAD

**Issue by WilsonKathleen** [WrightJosh/SeniorProject#4]
Can we add a search capability? i.e. so we can enter the Subject CN of a cert and find it?

**Comment by MasonSchneider** [comment]
![Search image](http://i.imgur.com/L5DJr6l.png)

Sorry, just wanted to make sure you saw the search we have. If you saw it, what do you mean by Subject CN compared to what is currently done? That is, searching by authority name and their supported regions then searching cert names once an authority is selected.

Thanks for the feedback!

**Comment by WilsonKathleen** [comment]
Wow. Somehow I completely missed the search bar at the top of the windows. Maybe due to my color blindness (I can see color, just not all shades). 

I like that you can also search by supported region. Nice!

The specific use case I had was that I wanted to find a particular cert, but I couldn't remember who owned it. For instance, the "IGC/A" certificate. But that's probably not a very common use case. It's probably safe to assume that someone looking for a particular cert has access to the certificate's Issuer Field.  So, this is probably low priority.

If you add help text to the windows, it would be great to have help text for the search to indicate that in the Authorities window users can search by Authority or Region.

**Comment by MasonSchneider** [comment]
I've made a new issue [here](https://github.com/WrightJosh/SeniorProject/issues/10) to help with communicating the use of the search bar. I think the owner search is covered in the issue [here](https://github.com/WrightJosh/SeniorProject/issues/8) so I'll close this issue unless I've missed another takeaway from this.
