### ISSUE TITLE
Update to latest version of IncludedCACertificateReportCSVFormat

### ISSUE THREAD

**Issue by WilsonKathleen** [WrightJosh/SeniorProject#43]
The 'Krajowa Izba Rozliczeniowa S.A.' CA was included in Firefox 46. The information for it (last audit, geographic focus, owner) can be found here:
https://mozillacaprogram.secure.force.com/CA/IncludedCACertificateReportCSVFormat

Rather than just update the data, would you please figure out a way for me to be able to update the information myself? 

I will need to maintain this information after you graduate, so I will need detailed instructions, and will need to test that I can do the update. I use Mac OS X El Capitan.

**Comment by mozkeeler** [comment]
@WilsonKathleen, I have a branch with updated documentation at https://github.com/mozkeeler/FirefoxCertificateManager/tree/doc-update/SalesForce%20Generator - is this sufficient? Or should I go into more detail?

**Comment by WilsonKathleen** [comment]
Hi David,
The important question is if you are able to update the xpi with the current Salesforce data. Is the documentation at the link you listed and in the "Getting Started for Developers" wiki instructions sufficient?
If yes, would you please update the xpi with the latest Salesforce data?
As long as you are able to do this, then you can show me how later.
Thanks,
Kathleen

**Comment by burchtm** [comment]
Kathleen,

The "Getting Started For Developers" does not currently have the documentation to do this in it. I am looking into how to try to do this step automatically with the XPI generation but haven't been able to look into it to much yet. There is a README.md file in the SalesForceGenerator folder that explains how to run the generator and where to put the file after it is ran. After the file is update you just have to run "jpm XPI" again to make a new XPI. 

One of us will outline that clearer in updated documentation and I will make sure the XPI has updated data next week.

**Comment by burchtm** [comment]
When I wrote last Friday I was off campus on m phone and did not have a chance to look at Davids new documentation. I just took a look at it and think it is great if Kathleen is good with it. If so, I will update the "Getting Started" documentation to point to this information or just copy the contents to that document. Once the steps in David's documentation are complete the the XPI just has to be regenerated and the new data will be present in the addon. 

I can still try to look into a way of getting this data auto-generated whenever an XPI is created but have not been able to work on this to much yet. @mozkeeler would you have any ideas on how this might be done? Is there a way to automatically call a shell script when packaging the XPI?

**Comment by burchtm** [comment]
I have updated the "Getting Started For Developers" document with the documentation @mozkeeler created. I modified it slightly but not much. Most changes were wording changes pertaining to the context of the section in the document.

**Comment by WilsonKathleen** [comment]
OK to close this issue as resolved. 
Data has been updated, and @mozkeeler can generate the updated xpi file with the updated SalesForce data and will show me how to do this later.
