### ISSUE TITLE
Rename one of the VIEW buttons

### ISSUE THREAD

**Issue by WilsonKathleen** [WrightJosh/SeniorProject#46]
The "VIEW..." and "VIEW ALL" buttons are next to each other, but do very different things. I think the one of those buttons should be renamed.

Brainstorming, here's some possibilities:
"VIEW ALL" -> "LIST ALL"
or
"VIEW..." -> "VIEW DETAILS"
"VIEW..." -> "SHOW DETAILS"
"VIEW..." -> "SHOW CERT"

**Comment by cheungnj** [comment]
We have changed the buttons based on your recommendations.
"VIEW ALL" -> "LIST ALL"
"VIEW..." -> "SHOW CERT"
