### ISSUE TITLE
Back Button From Show All To Authority Detail View Malfunctions

### ISSUE THREAD

**Issue by burchtm** [WrightJosh/SeniorProject#49]
If you use the back button to go from the Show All view to the view of all certificates for an authority the authorities table is loaded instead of the certificates that should.

**Comment by cheungnj** [comment]
I think this is due to the back button having a static href that points to index.html

**Comment by burchtm** [comment]
After changeset 45219e4 the href now uses parameters to handle loading different views.

**Comment by burchtm** [comment]
I believe that this is a .toggle issue caused from not having a check for if the right table is already loaded when the view is loaded.

**Comment by burchtm** [comment]
There was a missing if statement on what table to toggle when going to this page. Because of this the table holding the correct information was being toggle off instead of on and the main table was doing the opposite.
