### ISSUE TITLE
Ability to easily recover from "DELETE OR DISTRUST.." 

### ISSUE THREAD

**Issue by WilsonKathleen** [WrightJosh/SeniorProject#7]
Please make sure I can easily see which certs I have deleted/distrusted using the  "DELETE OR DISTRUST.." button, so I can revert the change.

**Comment by WilsonKathleen** [comment]
This is actually a significant issue. 

The way Distrust happens for an Authority is good -- it turns off the trust flags for the certs, but the certs are still there when you click on "View Certificates".

But when you click on "DELETE OR DISTRUST..." for a cert, it disappears. So, there is no recovery for the user, and no apparent way for the user to see what they did.

My recommendation is to change "DELETE or DISTRUST..." to "DISTRUST..." and have it turn off all of the trust bits for that cert, but leave the cert visible.

**Comment by MasonSchneider** [comment]
I think we have moved to this method in our code but haven't changed the text. I'll be updating the xpi file tonight after I take a look and verify.

**Comment by WilsonKathleen** [comment]
I'm still running the version that you sent me via email before the holidays.
Would you please email the xpi file when I should pick up the new version?

**Comment by MasonSchneider** [comment]
Sure thing! I'll start emailing you new versions every Tuesday night (end of our sprint).
