### ISSUE TITLE
Add Owner to Authorities detail

### ISSUE THREAD

**Issue by WilsonKathleen** [WrightJosh/SeniorProject#8]
Please add Owner to the detail that is shown when the user clicks on an Authority, and make it searchable. i.e. the same way you have Country.

This way, someone can find all of the Authorities owned by a particular CA, such as Symantec.

The Owner is in the first column of the Included CAs spreadsheet: https://mozillacaprogram.secure.force.com/CA/IncludedCACertificateReportCSVFormat

An example would be when you click on Equifax it would show:
Owner: Symantec / GeoTrust
Last Audit: 2015.05.05
Country: Global
TrustBits:  EMAIL

And if someone searched on Symantec they would find the Authorities for Equifax, GeoTrust, Thawte, and VeriSign.

**Comment by MasonSchneider** [comment]
I've added owner to the view and made it a criteria for searching. I also updated our salesforce data and noticed a couple of removed CAs. Should we keep old data like that or remove them as they are removed from the builtin certs?

**Comment by WilsonKathleen** [comment]
My recommendation is to update your data with each release milestone, so that it also reflects the new certs that have been added.
https://wiki.mozilla.org/RapidRelease/Calendar

Where is your copy of the BuiltIn CAs data stored?
How does it get updated?

**Comment by WilsonKathleen** [comment]
Note: I'm not a developer anymore, but if you provide instructions to me about how to update the data, I can add that to my list of things to maintain. (if it's not something that can be automated)

**Comment by MasonSchneider** [comment]
We currently download the CSV, run a python script, and paste the output to a file. We can simplify this and also make it maintain data removed from the builtin salesforce info. Could this just be done by using the removed CA salesforce CSV from [here](https://mozillacaprogram.secure.force.com/CA/RemovedCACertificateReport)? By joining this page and builtinCA CSV do we have all of the CA data you would like or is there more we need to keep such as other deleted items.

**Comment by WilsonKathleen** [comment]
You also have to take into account the added roots; and the trust bits and audit data get changed too. I think it would be better to always directly use https://mozillacaprogram.secure.force.com/CA/IncludedCACertificateReportCSVFormat and the python script and paste the output into the file -- just completely replace the contents of the file after each release. This sounds like something I can do after each Firefox release, as long as I have the instructions about what to do. It would be best to add the instructions to a file in github.

**Comment by MasonSchneider** [comment]
We can definitely do that. This means that the Salesforce data for CAs that are removed will be lost on every update. Is that ok?

**Comment by WilsonKathleen** [comment]
Yes, I think that's OK, because the Source in the Authorities list will show ? (if all their roots were removed). For the Authorities with ? I think it is fine for Audit, Owner, Geographic focus to say UNKNOWN.
