### ISSUE TITLE
Indicate which Authorities have been Distrusted

### ISSUE THREAD

**Issue by WilsonKathleen** [WrightJosh/SeniorProject#9]
After I distrust an Authority and refresh the window, there is no indication as to which Authority I distrusted. 

My recommendation is to update the TRUST % to show that the Authority has been distrusted.

**Comment by MasonSchneider** [comment]
We were unsure on this since we thought we wanted the trust indicator to reflect the authority and not local settings. What if we changed the background color of the distrusted row?

**Comment by WilsonKathleen** [comment]
That sounds like a reasonable solution too. Just need some obvious way for users to see which Authorities they have distrusted.
